extends:
- eslint:recommended
- plugin:import/recommended
- plugin:mozilla/recommended
- plugin:react/recommended

env:
  browser: true
  es6: true
  jquery: true

parserOptions:
  ecmaVersion: 6

root: true

rules:
  arrow-parens: off
  comma-dangle: off
  function-paren-newline: off
  guard-for-in: off
  import/no-named-as-default: off
  import/prefer-default-export: off
  linebreak-style: off
  no-multi-assign: off
  no-plusplus: off
  no-restricted-syntax: off
  no-use-before-define: off
  object-curly-newline: off
  react/prop-types: off

overrides:
  -
    files: ['src/**/*.js']
    globals:
      process: true
      require: true
  -
    files: ['src/extension/**/*.js']
    env:
      webextensions: true
  -
    files: ['webpack.*.js']
    rules:
      import/unambiguous: off
    env:
      node: true
